name: CI with report

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'npm'
      - run: npm ci

      - name: Run test and generate report
        run: npm run test:patterns

      - name: Upload report
        uses: actions/upload-artifact@v3
        with: 
          name: report
          if-no-files-found: error
          path: ./jest-html-report
          
      - name: Send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: -4269860473 # -4269860473
          token: ${{ secrets.TELEGRAM_BOT }}
          photo: ./test.png
          message: |
            ${{ github.actor }} created commit new view:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './jest-html-report'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1